language: java
sudo: true
dist: xenial
jdk:
  - openjdk12
services:
  - mongodb
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
install:
  - "./gradlew build --stacktrace --info"
notifications:
  email:
    on_success: never
    on_error: never
    on_failure: never
